version: '3'
services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:latest
    volumes:
      - /data/postgres:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: pgresUser
      POSTGRES_PASSWORD: pgresPW
      POSTGRES_DB: keycloakDB
    network_mode: host
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloakDB
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: pgresUser
      KC_DB_PASSWORD: pgresPW
      KC_PROXY: edge
    ports:
      - "8080:8080"
    network_mode: host
    command:
      - start-dev
    restart: unless-stopped
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf:Z
      - /data/tls:/etc/nginx/ssl:Z
    ports:
     - "80:80"
     - "443:443"
    network_mode: host
    restart: unless-stopped
